// St. Louis de Montfort — Fourth Method content.
// Each of the ten Hail Marys of a decade receives its own meditation,
// a progression of ten points through the mystery.

export const METHOD4_MEDITATIONS = {
  joyful: [
    // 1. Annunciation
    [
      "The eternal Father sends the archangel Gabriel to Nazareth.",
      "Gabriel enters the quiet dwelling of the humble Virgin.",
      "Hail, full of grace, the Lord is with thee.",
      "Mary is troubled at the angel's words and ponders them.",
      "Fear not, Mary, for thou hast found grace with God.",
      "Thou shalt conceive and bring forth a Son, and shalt call His name Jesus.",
      "How shall this be, since I know not man?",
      "The Holy Spirit shall come upon thee, and the power of the Most High overshadow thee.",
      "Behold the handmaid of the Lord; be it done unto me according to thy word.",
      "The Word is made flesh and dwells among us; we adore the Incarnation.",
    ],
    // 2. Visitation
    [
      "Mary rises and journeys with haste to the hill country.",
      "She carries Christ already living within her womb.",
      "She enters the house of Zachary and salutes Elizabeth.",
      "The infant John leaps in his mother's womb at the presence of Christ.",
      "Elizabeth, filled with the Holy Spirit, cries out with a loud voice.",
      "Blessed art thou among women, and blessed is the fruit of thy womb.",
      "Whence is this to me, that the mother of my Lord should come to me?",
      "Mary proclaims the greatness of the Lord in her Magnificat.",
      "She abides with Elizabeth in humble charity about three months.",
      "We learn to carry Christ to others with haste and love.",
    ],
    // 3. Nativity
    [
      "Joseph and Mary journey to Bethlehem to be enrolled.",
      "There is no room for them in the inn; the world has no place for Christ.",
      "They find shelter in a poor and humble stable.",
      "The hour of Mary's deliverance comes upon them.",
      "She brings forth her firstborn Son and wraps Him in swaddling clothes.",
      "She lays Him in a manger, the bread of life among beasts.",
      "Angels appear in the night to keep watch over the shepherds.",
      "Behold, I bring you tidings of great joy: a Saviour is born to you.",
      "The shepherds go with haste and find Mary, Joseph, and the Child.",
      "Mary keeps all these things, pondering them in her heart.",
    ],
    // 4. Presentation
    [
      "The days of Mary's purification are accomplished.",
      "Joseph and Mary bring the Child to Jerusalem to present Him to the Lord.",
      "They offer the humble gift of two turtle doves.",
      "Simeon, just and devout, awaits the consolation of Israel.",
      "The Holy Spirit has revealed that he shall not die before seeing the Christ.",
      "Led by the Spirit he comes into the temple and takes the Child into his arms.",
      "Now thou dost dismiss thy servant, Lord, in peace, for mine eyes have seen Thy salvation.",
      "A light to the revelation of the Gentiles, and the glory of Thy people Israel.",
      "Simeon blesses them and prophesies a sword of sorrow for Mary.",
      "Anna the prophetess gives thanks and speaks of the Child to all who await redemption.",
    ],
    // 5. Finding in the Temple
    [
      "Joseph and Mary go up to Jerusalem for the feast of the Passover.",
      "When the days are over, they return, supposing the Child to be among their kinsfolk.",
      "After a day's journey they seek Him among their acquaintances.",
      "Not finding Him, they return to Jerusalem with anxious hearts.",
      "After three days they find Him in the temple.",
      "He is sitting in the midst of the doctors, listening and asking questions.",
      "All who hear Him are astonished at His wisdom and His answers.",
      "Son, why hast thou done this to us? Thy father and I have sought thee sorrowing.",
      "Did you not know that I must be about my Father's business?",
      "He goes down to Nazareth with them and is subject to them; Mary keeps all these words.",
    ],
  ],
  sorrowful: [
    // 1. Agony in the Garden
    [
      "Jesus goes forth with His disciples across the brook Cedron.",
      "He enters the garden of Olives, a place of prayer and of betrayal.",
      "He begins to fear and to be heavy; sorrow even unto death weighs upon Him.",
      "He falls upon His knees and prays that the chalice may pass from Him.",
      "Father, if Thou wilt, remove this chalice from Me.",
      "Yet not My will, but Thine be done.",
      "There appears an angel from heaven strengthening Him.",
      "Being in an agony, He prays the longer; His sweat becomes as drops of blood.",
      "He rises to meet the traitor who comes with a kiss.",
      "He is seized and led away; the disciples forsake Him and flee.",
    ],
    // 2. Scourging
    [
      "Jesus is brought bound before Pilate, the Roman governor.",
      "Pilate questions Him and finds no cause of death in Him.",
      "To content the people, he delivers Jesus to be scourged.",
      "The soldiers lead Him into the hall of the praetorium.",
      "They strip Him of His garments and bind Him to the pillar.",
      "With cruel cords they lash His sacred flesh from head to foot.",
      "Under each stroke He suffers in silence, offering Himself for our sins.",
      "His blood flows down upon the ground; His body is rent for our healing.",
      "By His stripes we are healed; each wound is an act of love.",
      "He is unbound, clothed again, and led forth, a man of sorrows.",
    ],
    // 3. Crowning with Thorns
    [
      "The soldiers gather the whole cohort about Jesus in the hall.",
      "They strip Him again and throw a scarlet cloak over His shoulders.",
      "They plait a crown of sharp thorns and press it upon His head.",
      "They put a reed into His right hand as a sceptre.",
      "They bend the knee before Him in mockery.",
      "Hail, King of the Jews, they cry, striking Him with their hands.",
      "They spit upon His face and buffet His head with the reed.",
      "The thorns pierce His brow; His sacred blood flows down.",
      "True King of glory, He hides His majesty beneath the mockery of men.",
      "We adore the patience of our King crowned for love of us.",
    ],
    // 4. Carrying the Cross
    [
      "Pilate delivers Jesus to be crucified; He is led out to Calvary.",
      "The heavy cross is laid upon His wounded shoulders.",
      "He begins the way of sorrows, bearing the wood of our redemption.",
      "Weakened by His agony and scourging, He falls beneath the weight.",
      "He meets His Mother; their eyes speak a grief beyond all words.",
      "Simon of Cyrene is seized and made to help bear the cross.",
      "Veronica offers her veil; the holy face is imprinted upon it.",
      "Jesus turns to the women of Jerusalem and bids them weep for their sins.",
      "He falls again and again, rising each time for love of us.",
      "He reaches Calvary and is stripped of His garments for crucifixion.",
    ],
    // 5. Crucifixion
    [
      "They lay the cross upon the ground and stretch Jesus upon it.",
      "They drive the nails through His hands and His sacred feet.",
      "They raise the cross and let it fall into its place.",
      "Father, forgive them, for they know not what they do.",
      "Mary stands beneath the cross with John and the holy women.",
      "Woman, behold thy son; behold thy mother.",
      "The rulers and soldiers deride Him, saving Himself now if He will.",
      "I thirst, He cries, fulfilling the Scripture in His suffering.",
      "It is consummated; the work of our redemption is accomplished.",
      "Father, into Thy hands I commend My spirit; He bows His head and dies.",
    ],
  ],
  glorious: [
    // 1. Resurrection
    [
      "On the third day, before the dawn, the earth trembles and the guards are struck with fear.",
      "An angel descends from heaven and rolls back the stone from the door.",
      "Christ rises in glory, leaving the tomb empty and His burial cloths folded.",
      "He is the firstborn from the dead, conqueror of sin and death.",
      "The holy women come to the sepulchre to anoint Him at daybreak.",
      "They find the stone rolled away and hear the angel's tidings.",
      "Why seek you the living among the dead? He is risen, as He said.",
      "He appears to Mary Magdalene in the garden, calling her by name.",
      "He appears to the apostles in the upper room, showing His wounds.",
      "Peace be with you; because I live, you also shall live.",
    ],
    // 2. Ascension
    [
      "The risen Lord abides with His disciples forty days, teaching them.",
      "He opens their minds to understand the Scriptures.",
      "He leads them out toward Bethany and lifts up His hands in blessing.",
      "All power is given to Me in heaven and on earth; go and teach all nations.",
      "I am with you all days, even to the consummation of the world.",
      "He is taken up before their eyes; a cloud receives Him from their sight.",
      "They gaze after Him into heaven, filled with awe and joy.",
      "Two angels stand beside them: this Jesus shall so come as you have seen Him go.",
      "He sits at the right hand of the Father to intercede for us.",
      "We await His return in glory, lifting up our hearts to heaven.",
    ],
    // 3. Descent of the Holy Spirit
    [
      "The apostles return to Jerusalem and abide in the upper room with Mary.",
      "With one accord they persevere in prayer, awaiting the promised Spirit.",
      "When the day of Pentecost is fully come, they are all together in one place.",
      "A sound from heaven comes as of a mighty wind and fills the house.",
      "Cloven tongues as of fire appear and rest upon each of them.",
      "They are all filled with the Holy Spirit.",
      "They begin to speak in other tongues as the Spirit gives them utterance.",
      "Devout Jews of every nation hear them, each in his own language.",
      "Peter, strengthened by the Spirit, preaches and three thousand are baptized.",
      "The Church is born; the Spirit abides with her unto the end of the age.",
    ],
    // 4. Assumption
    [
      "At the end of her earthly life, Mary is surrounded by the apostles.",
      "Her soul, immaculate and full of grace, is taken by her Son.",
      "Her body, which bore the living God, is not left to corruption.",
      "She is assumed body and soul into the glory of heaven.",
      "She follows where her Son went before, the first redeemed in body and soul.",
      "The Ark of the New Covenant is brought into the heavenly sanctuary.",
      "The Queen stands at the right hand of the King in golden raiment.",
      "She is the sign and pledge of the glory awaiting all the faithful.",
      "We rejoice in her triumph, our Mother taken into the Father's house.",
      "We beseech her to prepare us for our own passage to eternal life.",
    ],
    // 5. Coronation
    [
      "Mary is received into heaven with great rejoicing of the angels and saints.",
      "The Father welcomes her as the daughter of His good pleasure.",
      "The Son crowns her with a crown of twelve stars, queen of angels and men.",
      "She is seated at the right hand of her Son in a throne of glory.",
      "Hail, Queen of Heaven; hail, Mistress of the angels.",
      "She is crowned Queen of mercy, of peace, and of grace.",
      "She reigns not to command, but to intercede as our loving Mother.",
      "All generations shall call her blessed, now and forever.",
      "From her throne she dispenses the graces of her Son to all who ask.",
      "We trust in her maternal protection unto the end of our days.",
    ],
  ],
  luminous: [
    // 1. Baptism
    [
      "Jesus comes from Galilee to the Jordan, to John, to be baptized.",
      "John would hinder Him: I ought to be baptized by Thee.",
      "Suffer it now, for so it becomes us to fulfill all justice.",
      "Jesus descends into the waters, taking upon Him the sins of the world.",
      "The heavens open above Him as He prays.",
      "The Spirit of God descends like a dove and rests upon Him.",
      "A voice from heaven proclaims: This is My beloved Son, in whom I am well pleased.",
      "The Father, the Son, and the Holy Spirit are revealed together.",
      "We remember our own baptism and the dignity of being children of God.",
      "We pray for the grace to live as sons and daughters of the Father.",
    ],
    // 2. Cana
    [
      "There is a wedding at Cana of Galilee, and the Mother of Jesus is there.",
      "Jesus and His disciples are also invited to the marriage.",
      "The wine fails; Mary perceives the need before it is spoken.",
      "She turns to her Son: They have no wine.",
      "Woman, what is that to Me and to thee? My hour is not yet come.",
      "She trusts and says to the servants: Whatsoever He shall say to you, do it.",
      "Jesus bids them fill the water pots with water, and they fill them to the brim.",
      "Draw out now, and carry to the chief steward.",
      "The water is made wine, the first of His signs, manifesting His glory.",
      "Through Mary's intercession, His disciples believe in Him.",
    ],
    // 3. Proclamation of the Kingdom
    [
      "Jesus comes into Galilee, preaching the Gospel of the kingdom of God.",
      "The time is accomplished; the kingdom of God is at hand.",
      "Repent and believe the Gospel, He calls to every soul.",
      "He teaches with authority, as one having power, and not as the scribes.",
      "He welcomes sinners and eats with them, showing the Father's mercy.",
      "He heals the sick, gives sight to the blind, and raises the dead.",
      "He calls the Twelve to be with Him and to be sent forth to preach.",
      "The kingdom is a mustard seed, growing to shelter the birds of the air.",
      "The kingdom is leaven hidden in the meal, transforming all.",
      "We pray: Thy kingdom come, Thy will be done, on earth as it is in heaven.",
    ],
    // 4. Transfiguration
    [
      "Jesus takes Peter, James, and John and leads them up a high mountain.",
      "He is transfigured before them; His face shines as the sun.",
      "His garments become white as the light, exceeding all whiteness.",
      "There appear Moses and Elijah, speaking with Him of His departure.",
      "Peter, not knowing what to say, proposes to make three tents.",
      "A bright cloud overshadows them; they fall on their faces in fear.",
      "This is My beloved Son, in whom I am well pleased; hear ye Him.",
      "They lift up their eyes and see no one but Jesus only.",
      "As they come down, He bids them tell the vision to no one until He rises.",
      "We pray for the grace to listen to Christ and to follow Him to the cross.",
    ],
    // 5. Institution of the Eucharist
    [
      "On the night before He died, Jesus desires to eat the Passover with His own.",
      "He rises from supper and washes His disciples' feet in humility.",
      "He takes bread, and blessing it, breaks it and gives it to them.",
      "Take ye and eat; this is My body, which is given for you.",
      "He takes the chalice and gives thanks, and gives it to them.",
      "Drink ye all of it, for this is My blood of the new testament.",
      "This is shed for many for the remission of sins.",
      "Do this in commemoration of Me, He commands, instituting the priesthood.",
      "He gives Himself completely, the bread of life and the cup of salvation.",
      "We pray for love of the Eucharist and for worthy reception of His body.",
    ],
  ],
};

export const getMethod4Meditation = (mysterySet, decade, hailMaryNumber) => {
  const decadeList = METHOD4_MEDITATIONS[mysterySet]?.[decade - 1];
  return decadeList && hailMaryNumber ? decadeList[hailMaryNumber - 1] : null;
};
